import type { PrefilterConfig } from '@gamestock/domain';

/**
 * Thresholds are deliberately in code (not the database) so changes are
 * reviewable. Every rule here runs on data the category page already gives us,
 * so rejecting a listing costs nothing.
 */
export const PREFILTER: Record<string, PrefilterConfig> = {
  'clash-royale': {
    minSellerRating: 4,
    minSellerReviews: 0,
    minSellerAgeMonths: 0,
    allowUnknownSellerRating: true,
    allowUnknownSellerAge: true,
    minPrice: 300,
    maxPrice: 8000,
    priceCurrency: 'RUB',
    minTrophies: 7000,
    minCards: 100,
    requireAutoDelivery: false,
  },
  'pubg-mobile': {
    minSellerRating: 5,
    minSellerReviews: 0,
    minSellerAgeMonths: 0,
    allowUnknownSellerRating: false,
    allowUnknownSellerAge: true,
    minPrice: 300,
    maxPrice: 100_000,
    priceCurrency: 'RUB',
    minAccountLevel: 50,
    requireAutoDelivery: false,
  },
  'car-parking-multiplayer': {
    minSellerRating: 4,
    minSellerReviews: 0,
    minSellerAgeMonths: 0,
    allowUnknownSellerRating: false,
    allowUnknownSellerAge: true,
    minPrice: 0,
    maxPrice: 1_000_000,
    priceCurrency: 'RUB',
    requireAutoDelivery: false,
  },
  'arknights-endfield': {
    minSellerRating: 0,
    minSellerReviews: 0,
    minSellerAgeMonths: 0,
    allowUnknownSellerRating: true,
    allowUnknownSellerAge: true,
    minPrice: 2_000,
    maxPrice: 100_000,
    priceCurrency: 'RUB',
    requireAutoDelivery: false,
  },
  'standoff-2': {
    minSellerRating: 4,
    minSellerReviews: 0,
    minSellerAgeMonths: 0,
    allowUnknownSellerRating: false,
    allowUnknownSellerAge: true,
    minPrice: 700,
    maxPrice: 500_000,
    priceCurrency: 'RUB',
    requireAutoDelivery: false,
  },
  'eldorado-179': {
    minSellerRating: 0,
    minSellerReviews: 0,
    minSellerAgeMonths: 0,
    allowUnknownSellerRating: true,
    allowUnknownSellerAge: true,
    minPrice: 300,
    maxPrice: 150_000,
    priceCurrency: 'RUB',
    requireAutoDelivery: false,
  },
  'eldorado-166': {
    minSellerRating: 0,
    minSellerReviews: 0,
    minSellerAgeMonths: 0,
    allowUnknownSellerRating: true,
    allowUnknownSellerAge: true,
    minPrice: 300,
    maxPrice: 150_000,
    priceCurrency: 'RUB',
    requireAutoDelivery: false,
  },
};
